---
language: node_js
node_js:
  - "6"

sudo: false
dist: trusty

env:
  - CXX=g++-4.8

addons:
  chrome: stable
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - xvfb
      - g++-4.8

cache:
  yarn: true
  directories:
    - $HOME/.npm

before_install:
  - npm config set spin false
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.27.5
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn config set no-progress

install:
  - yarn
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
