---
language: node_js
node_js:
  - "6"

os:
  - linux
    dist: trusty
    sudo: required
  - osx

env:
  - CXX=g++-4.8

addons:
  chrome: stable
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - xvfb
      - g++-4.8
      - fakeroot
      - rpm

cache:
  yarn: true
  directories:
    - $HOME/.npm
    - node_modules

stages:
  - name: after_success
    # only want to deploy if master build
    if: branch = master

before_install:
  - npm config set spin false
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gcc48 --enable-cxx ; fi

install:
  - npm install
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=':99.0' ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 & ; fi

before_script:
  - npm install -g bower
  - npm install -g coveralls
  - npm install -g firebase-tools
  - bower install

after_success:
  - cat coverage/lcov.info | coveralls
  - ember build
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; travis_wait 30 ember electron:make --platform linux -prod --arch ia32 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; travis_wait 30 ember electron:make --platform linux -prod --arch x64 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; travis_wait 30 ember electron:make --platform osx -prod --arch ia32 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; travis_wait 30 ember electron:make --platform osx -prod --arch x64 ; fi
  - firebase deploy --token "$FIREBASE_TOKEN"
