---
language: node_js
node_js:
  - "6"

sudo: required
dist: trusty

matrix:
  allow_failures:
    - os: osx
  include:
    - os: linux
      env:
        - DISPLAY=:99.0
        - CC=clang
        - CXX=clang++
        - npm_config_clang=1
        - TARGET_ARCH=x64
        - OS=LINUX
    - os: osx
      osx_image: xcode7.3
      env:
        - TARGET_ARCH=x64
        - OS=DARWIN
        - DISPLAY=:99.0

addons:
  chrome: stable
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - xvfb
      - g++-4.8
      - fakeroot
      - rpm

cache:
  yarn: true
  directories:
    - $HOME/.npm
    - node_modules

stages:
  - name: after_success
    # only want to build if master build
    if: branch = master
  - name: before_deploy
    # only want to deploy if master build
    if: branch = master
  - name: deploy
    # only want to deploy if master build
    if: branch = master

before_install:
  - npm config set spin false

install:
  - npm install
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

before_script:
  - npm install -g bower
  - npm install -g coveralls
  - npm install -g firebase-tools
  - npm install -g node-gyp
  - bower install

after_success:
  - cat coverage/lcov.info | coveralls
  - ember build
  - if [ "$OS" = "LINUX" ]; then travis_wait 90 ember electron:make --platform linux -prod --arch ia32 --name Ordino; fi
  - if [ "$OS" = "LINUX" ]; then travis_wait 90 ember electron:make --platform linux -prod --arch x64 --name Ordino; fi
  - if [ "$OS" = "DARWIN" ]; then travis_wait 90 ember electron:make --platform darwin -prod --arch ia32 --name Ordino; fi
  - if [ "$OS" = "DARWIN" ]; then travis_wait 90 ember electron:make --platform darwin -prod --arch x64 --name Ordino; fi
  - ls electron-out/make
  - firebase deploy --token "$FIREBASE_TOKEN"

before_deploy:
  - git config --local user.name "Adam Ward (Travis CI)"
  - git config --local user.email "adam.ward@carleton.ca"
  - git tag "1.0.0-$(git log --format=%h -1)"

deploy:
  provider: releases
  api_key: $GH_RELEASE_TOKEN
  file:
    - electron-out/make/Ordino_1.0.0_amd64.deb
    - electron-out/make/Ordino_1.0.0_i386.deb
  skip_cleanup: true
