---
language: node_js
node_js:
  - "6"

sudo: required
dist: trusty

env:
  - CXX=g++-4.8

addons:
  chrome: stable
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - xvfb
      - g++-4.8
      - fakeroot
      - rpm

cache:
  yarn: true
  directories:
    - $HOME/.npm
    - node_modules

stages:
  - name: after_success
    # only want to deploy if master build
    if: branch = master

before_install:
  - npm config set spin false

install:
  - npm install
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

before_script:
  - npm install -g bower
  - npm install -g coveralls
  - npm install -g firebase-tools
  - bower install

after_success:
  - cat coverage/lcov.info | coveralls
  - ember build --environment production
  - travis_wait 30 ember electron:make --platform linux -prod --arch ia32
  - travis_wait 30 ember electron:make --platform linux -prod --arch x64
  - firebase deploy --token "$FIREBASE_TOKEN"
