---
sudo: required
os:
- linux
- osx
dist: trusty
osx_image: xcode8
language: node_js
node_js:
- '6'

env:
  - CXX=g++-4.8
  global:
    # prevent wine popup dialogs about installing additional packages
    - WINEDLLOVERRIDES="mscoree,mshtml="
    - WINEDEBUG="-all"

addons:
  chrome: stable
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - xvfb
      - g++-4.8
      - wine

cache:
  - apt: true
  - yarn: true
  - directories:
    - $HOME/.electron
    - $HOME/.npm
    - node_modules

before_install:
  -
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      - openssl req -newkey rsa:4096 -days 1 -x509 -nodes -subj "/C=CI/ST=Travis/L=Developer/O=Developer/CN=Developer CA" -out /tmp/root.cer -keyout /tmp/root.key
      - touch /tmp/certindex
      - sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain /tmp/root.cer
      - openssl req -newkey rsa:1024 -nodes -subj "/C=CI/ST=Travis/L=Developer/O=Developer/CN=Developer CodeCert" -out codesign.csr -keyout codesign.key
      - openssl ca -batch -config $(pwd)/test/ci/dev_ca.cnf -notext -create_serial -in codesign.csr -out codesign.cer
      - openssl pkcs12 -export -in codesign.cer -inkey codesign.key -out codesign.p12 -password pass:12345
      - security import codesign.p12 -k ~/Library/Keychains/login.keychain -P 12345 -T /usr/bin/codesign
      - npm install wine-darwin@1.9.17-1
      - ./node_modules/.bin/wine hostname
      - npm install -g yarn
    fi
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      - npm config set spin false
      - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.27.5
      - export PATH=$HOME/.yarn/bin:$PATH
      - yarn config set no-progress
      - sudo rm /etc/apt/sources.list.d/google-chrome.list
      - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
      - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
      - sudo dpkg --add-architecture i386
      - sudo apt-get update
      - sudo apt-get install -y wine1.6 yarn
    fi
  - npm install -g cnpm

branches:
  only:
  - master

install:
  - yarn
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

before_script:
  - npm install -g bower
  - npm install -g coveralls
  - npm install -g firebase-tools
  - bower install

after_success:
  - cat coverage/lcov.info | coveralls
  - ember build
  - ember electron:make
  - firebase deploy --token "$FIREBASE_TOKEN"
