image: Visual Studio 2015

version: "{build}"

clone_depth: 1

init:
  - git config --global core.autocrlf true

branches:
  only:
  - master
  
skip_non_tags: true

platform:
  - x64

environment:
  matrix:
    - nodejs_version: "6"

cache:
  - node_modules -> package.json
  - '%APPDATA%\npm-cache'
  
install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - cmd: IF "%nodejs_version%"=="6" npm install -g npm@6
  - ps: iex ./install-advinst.ps1
  - npm config set spin false
  - npm install -g ember-cli@2.18.2
  - npm install -g bower
  - npm install -g node-gyp
  - npm install --no-optional --no-color --no-progress
  - bower install

build_script:
  - ember build
  - ember electron:package -prod --arch ia32
  - ember electron:package -prod --arch x64
  - ps: AdvancedInstaller.com /build Ordino-32bit.aip
  - ps: AdvancedInstaller.com /build Ordino-64bit.aip
  
deploy:
  release: $(APPVEYOR_REPO_TAG_NAME)
  provider: GitHub
  auth_token: $(GH_RELEASE_TOKEN)
  artifact: installers\Ordino-Windows-Installer-1.0.0-x86_64.msi,installers\Ordino-Windows-Installer-1.0.0-x86.msi
  draft: false
  prerelease: false
  on:
      appveyor_repo_tag: true
